#!/usr/bin/env bash
# Auto-generated by vaibify. Reproduces this workflow on a stock host.
# Requires: docker, jq, sha256sum.
set -euo pipefail

sImageRef=$(jq -r .dictContainer.sImageDigest \
    .vaibify/environment.json)
if [ -z "$sImageRef" ] || [ "$sImageRef" = "null" ]; then
    echo "error: sImageDigest missing from .vaibify/environment.json" >&2
    exit 2
fi

docker pull "$sImageRef"
docker run --rm -v "$PWD":/work -w /work "$sImageRef" bash -c '
  set -euo pipefail
  pip install --require-hashes -r requirements.lock
  # Step: TESS Flare Candidates
  ( cd 'TessFlareCandidates' && \
      python dataIdentifyFlareCandidates.py --output flare_candidates.json 
  )
  # Step: Kepler FFD Corner
  ( cd 'KeplerFfdCorner' && \
      python dataKeplerFfd.py && \
      python plotCornerVariableSlope.py {sPlotDirectory}/CornerVariableSlope.{sFigureType} 
  )
  # Step: FFD Age Comparison
  ( cd 'FfdAgeComparison' && \
      python plotFfdComparison.py --samples {Step02.flare_mcmc_samples} {sPlotDirectory}/ffd_comp.{sFigureType} 
  )
  # Step: TESS Flare Lightcurves
  ( cd 'TessFlareLightcurves' && \
      python plotFlareLightcurves.py --flare-candidates {Step01.flare_candidates} {sPlotDirectory}/GJ1132_flares.{sFigureType} 
  )
  # Step: Comprehensive FFD Comparison
  ( cd 'ComprehensiveFfdComparison' && \
      python plotComprehensiveFfd.py --flare-candidates {Step01.flare_candidates} --kepler-posterior {Step02.kepler_ffd_posterior_stats} {sPlotDirectory}/GJ1132_FFD_comp2.{sFigureType} 
  )
  # Step: XUV Luminosity Distribution
  ( cd 'XuvLuminosityDistribution' && \
      python dataLxuv.py && \
      python plotLxuv.py --output-directory {sPlotDirectory} --figure-type {sFigureType} 
  )
  # Step: Engle Age Distribution
  ( cd 'EngleAgeDistribution' && \
      python dataAge.py && \
      python plotAge.py {sPlotDirectory}/EngleAgeHist.{sFigureType} 
  )
  # Step: Maximum Likelihood
  ( cd 'MaximumLikelihood' && \
      maxlev gj1132_ribas.json 
  )
  # Step: Bayesian Posteriors
  ( cd 'BayesianPosteriors' && \
      python dataBayesianPosteriors.py --lxuv-constraints {Step06.lxuv_constraints} && \
      python plotSamplerComparison.py {sPlotDirectory}/sampler_comparison.{sFigureType} 
  )
  # Step: XUV Evolution
  ( cd 'XuvEvolution' && \
      python dataRunVconverge.py --flare-samples {Step02.flare_mcmc_samples} --age-samples {Step07.age_samples} --dynesty-samples {Step09.dynesty_transform_final} && \
      python plotXuvEvolution.py {sPlotDirectory}/XUVEvol.{sFigureType} 
  )
  # Step: Cumulative XUV and Cosmic Shoreline
  ( cd 'CumulativeXuvAndCosmicShoreline' && \
      python dataRunVconverge.py --age-samples {Step07.age_samples} --dynesty-samples {Step09.dynesty_transform_final} && \
      python plotCumulativeXuv.py {sPlotDirectory}/GJ1132b_CumulativeXUV_Multi.{sFigureType} --engle-barnes-converged {Step10.EngleBarnes_Converged_Param_Dictionary} --ribas-barnes-converged {Step10.RibasBarnes_Converged_Param_Dictionary} && \
      python plotCosmicShoreline.py {sPlotDirectory}/CosmicShoreline.{sFigureType} --engle-barnes-converged {Step10.EngleBarnes_Converged_Param_Dictionary} --ribas-barnes-converged {Step10.RibasBarnes_Converged_Param_Dictionary} 
  )
  # Step: Error Source Comparison
  ( cd 'ErrorSourceComparison' && \
      python dataRunVconverge.py --age-samples {Step07.age_samples} --dynesty-samples {Step09.dynesty_transform_final} && \
      python plotErrorSourceComparison.py {sPlotDirectory}/GJ1132b_ErrorSourceComparison.{sFigureType} --engle-converged {Step11.Engle_Converged_Param_Dictionary} --ribas-converged {Step11.Ribas_Converged_Param_Dictionary} 
  )
  # Step: Kepler vs TESS Comparison
  ( cd 'KeplerVsTessComparison' && \
      python plotKeplerVsTessComparison.py --flare-candidates {Step01.flare_candidates} --kepler-posterior {Step02.kepler_ffd_posterior_stats} {sPlotDirectory}/FitComparison.{sFigureType} 
  )
  sha256sum -c MANIFEST.sha256
'
