"""Qualitative tests generated by vaibify."""

import pytest


def test_lxuv_constraints_json_keys():
    import json
    import os
    sPath = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        'lxuv_constraints.json',
    )
    with open(sPath, encoding='utf-8') as fh:
        dictData = json.load(fh)
    assert 'dMean' in dictData
    assert 'dStd' in dictData

