"""Integrity tests generated by vaibify."""
import os
import numpy as np
import pytest

_STEP_DIRECTORY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def test_age_samples_exists():
    sPath = os.path.join(_STEP_DIRECTORY, 'age_samples.txt')
    assert os.path.isfile(sPath)
    assert os.path.getsize(sPath) > 0


def test_age_samples_loadable():
    sPath = os.path.join(_STEP_DIRECTORY, 'age_samples.txt')
    with open(sPath, encoding='utf-8') as fh:
        rows = [l for l in fh if l.strip() and not l.strip().startswith('#')]
    assert len(rows) >= 81975


def test_age_samples_no_nan():
    sPath = os.path.join(_STEP_DIRECTORY, 'age_samples.txt')
    with open(sPath, encoding='utf-8') as fh:
        for sLine in fh:
            s = sLine.strip()
            if not s or s.startswith('#'):
                continue
            for sToken in s.split():
                try:
                    fVal = float(sToken)
                    assert not np.isnan(fVal)
                    assert not np.isinf(fVal)
                except ValueError:
                    pass

