"""Quantitative benchmark tests generated by vaibify."""

import json
import pathlib

import numpy as np
import pytest


def _fdictParseAccessPath(sAccessPath):
    """Parse an access path into a dict with key, column, indices, and aggregate."""
    import re
    dictResult = {}
    matchKey = re.match(r"key:([^,]+)", sAccessPath)
    if matchKey:
        dictResult["key"] = matchKey.group(1)
    matchColumn = re.search(r"column:([^,]+)", sAccessPath)
    if matchColumn:
        dictResult["column"] = matchColumn.group(1)
    matchAggregate = re.search(r"index:(mean|min|max)", sAccessPath)
    if matchAggregate:
        dictResult["sAggregate"] = matchAggregate.group(1)
    else:
        matchIndex = re.search(r"index:([-\d,]+)", sAccessPath)
        if matchIndex:
            dictResult["listIndices"] = [
                int(x) for x in matchIndex.group(1).split(",")
                if x.strip()
            ]
    return dictResult


def _fLoadValue(sDataFile, sAccessPath, sStepDirectory):
    """Load a single value from a data file using the access path."""
    sFullPath = str(pathlib.Path(sStepDirectory) / sDataFile)
    dictAccess = _fdictParseAccessPath(sAccessPath)
    if sFullPath.endswith(".npy"):
        return _fLoadNumpyValue(sFullPath, dictAccess)
    if sFullPath.endswith(".json"):
        return _fLoadJsonValue(sFullPath, dictAccess)
    return _fLoadCsvValue(sFullPath, dictAccess)


def _fLoadNumpyValue(sFullPath, dictAccess):
    """Load a value from a numpy file."""
    daData = np.load(sFullPath)
    sAggregate = dictAccess.get("sAggregate")
    if sAggregate == "mean":
        return float(daData.mean())
    if sAggregate == "min":
        return float(daData.min())
    if sAggregate == "max":
        return float(daData.max())
    listIndices = dictAccess.get("listIndices", [-1])
    return float(daData[tuple(listIndices)])


def _fLoadJsonValue(sFullPath, dictAccess):
    """Load a value from a JSON file."""
    with open(sFullPath) as fileHandle:
        dictData = json.load(fileHandle)
    sKey = dictAccess.get("key", "")
    listKeys = sKey.split(".") if sKey else []
    value = dictData
    for sSubKey in listKeys:
        if isinstance(value, list):
            value = value[int(sSubKey)]
        else:
            value = value[sSubKey]
    listIndices = dictAccess.get("listIndices", None)
    if listIndices is not None:
        for iIdx in listIndices:
            value = value[iIdx]
    return float(value)


def _fLoadCsvValue(sFullPath, dictAccess):
    """Load a value from a CSV file."""
    import csv
    sColumn = dictAccess.get("column", "")
    listIndices = dictAccess.get("listIndices", [-1])
    iIndex = listIndices[0] if listIndices else -1
    with open(sFullPath, newline="") as fileHandle:
        reader = csv.DictReader(fileHandle)
        listRows = list(reader)
    return float(listRows[iIndex][sColumn])


def _fdictLoadStandardsFile():
    """Load the quantitative standards JSON file."""
    sJsonPath = str(
        pathlib.Path(__file__).parent / "quantitative_standards.json"
    )
    with open(sJsonPath) as fileHandle:
        return json.load(fileHandle)


_DICT_STANDARDS = _fdictLoadStandardsFile()
_F_DEFAULT_RTOL = _DICT_STANDARDS.get("fDefaultRtol", 1e-6)
_LIST_STANDARDS = _DICT_STANDARDS["listStandards"]
_STEP_DIRECTORY = str(pathlib.Path(__file__).parent.parent)


@pytest.mark.parametrize(
    "dictStandard",
    _LIST_STANDARDS,
    ids=[s["sName"] for s in _LIST_STANDARDS],
)
def test_quantitative_benchmark(dictStandard):
    """Compare output value against stored benchmark within tolerance."""
    fActual = _fLoadValue(
        dictStandard["sDataFile"],
        dictStandard["sAccessPath"],
        _STEP_DIRECTORY,
    )
    fExpected = dictStandard["fValue"]
    fRtol = dictStandard.get("fRtol", _F_DEFAULT_RTOL)
    fAtol = dictStandard.get("fAtol", 1e-08)
    assert np.allclose(fActual, fExpected, rtol=fRtol, atol=fAtol), (
        f"{dictStandard['sName']}: expected {fExpected}, got {fActual}"
    )
