"""Qualitative tests generated by vaibify."""

import pytest


def test_maxlike_results_columns():
    import os
    sPath = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        'maxlike_results.txt',
    )
    with open(sPath, encoding='utf-8') as fh:
        listCols = fh.readline().split()
    assert 'GJ1132_Ribas_XUV' in listCols
    assert 'Maximum' in listCols
    assert 'A' in listCols
    assert 'Posteriori' in listCols
    assert '(MAP)' in listCols
    assert 'Estimation' in listCols

